theme: 
    name: readthedocs
#    custom_dir: 'custom_theme/'

#    name: rtd-dropdown

markdown_extensions:
  - codehilite:
        linenums: true
    
site_name: MISCnn wiki
nav:
    - Home: 'Home.md'
    - Getting Started:
        - 'What is MIScnn?': 'Home.md'
        - 'Install': 'Install.md'
        - 'Basic Usage': 'Usage.md'
        - 'Tutorials': 'Tutorials.md'
        - 'Examples': 'Examples.md'
    - Documentation - Core:
        - 'Data I/O': 'Data-IO.md'
        - 'Preprocessor': 'Preprocessor.md'
        - 'Data Augmentation': 'Data-Augmentation.md'
        - 'Neural Network Model': 'Model.md'
        - 'Validation Techniques': 'Validation.md'
    - Documentation - Interfaces:
        - 'Architectures': 'Architectures.md'
        - 'Metrics': 'Metrics.md'
        - 'Subfunctions': 'Subfunctions.md'
        - 'I/O Interfaces': 'IO-Interfaces.md'
    - Documentation - Extras:
        - 'Sample': 'Sample.md'
    - Other:
        - 'How to Contribute': 'Contribute.md'
        - 'Author and Contacts': 'Credits.md'
        
